name: Coverity Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  coverity:
    runs-on: [self-hosted, Linux, X64, samples-java-Owen]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Coverity Local Scan
        run: |
          chmod +x -R ../samples-java_Owen
          ~/coverity/cov-analysis_2025_03/bin/cov-build --dir ../idir ./gradlew build
          ~/coverity/cov-analysis_2025_03/bin/cov-analyze --dir ../idir --all --all-security --aggressiveness-level high
